name: Deploy to Server

on:
  push:
    branches:
      - main  # or whichever branch you deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "."
          target: "/path/to/deployment/directory"  # change to your deployment folder

      - name: Restart Service on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /path/to/deployment/directory
            # Optionally, pull latest changes if you prefer a git-based update:
            # git pull origin main
            sudo systemctl restart your-service-name  # replace with your actual service name
